CONDA_BUILD_SYSROOT: ''
VERBOSE_AT: V=1
VERBOSE_CM: VERBOSE=1
arpack: 3.6.3
bamtools: 2.5.1
blas_impl: openblas
boost: 1.70.0
boost_cpp: 1.70.0
bzip2: '1'
c_compiler: gcc
c_compiler_version: '7'
cairo: '1.16'
cfitsio: '3.470'
cgo_compiler: go-cgo
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
curl: '7.64'
cxx_compiler: gxx
cxx_compiler_version: '7'
dbus: '1'
docker_image: condaforge/linux-anvil-comp7
expat: '2.2'
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_version
- ignore_build_only_deps
ffmpeg: '4.0'
flann: 1.9.1
fontconfig: '2.13'
fortran_compiler: gfortran
fortran_compiler_version: '7'
freetype: 2.9.1
gdal: '2.4'
gdk_pixbuf: 2.36.12
geos: 3.7.2
geotiff: 1.5.1
gf2x: '1.2'
giflib: 5.1.7
glew: 2.0.0
glib: '2.58'
glog: 0.4.0
glpk: '4.65'
gmp: '6'
go_compiler: go-nocgo
graphviz: 2.38.0
gsl: '2.5'
gst_plugins_base: 1.14.4
gstreamer: 1.14.4
harfbuzz: '2'
hdf4: '4.2'
hdf5: 1.10.5
htslib: '1.9'
icu: '58'
ignore_build_only_deps:
- numpy
- python
isl: '0.19'
jasper: 1.900.1
jpeg: '9'
json_c: '0.13'
jsoncpp: 1.8.4
kealib: 1.4.10
krb5: '1.16'
libblas: 3.8 *netlib
libblitz: '0.10'
libcblas: 3.8 *netlib
libcurl: '7.64'
libdap4: '3.19'
libdeflate: '1.0'
libevent: 2.1.10
libffi: '3.2'
libgdal: '2.4'
libiconv: '1.15'
libjpeg_turbo: '2'
libkml: '1.3'
liblapack: 3.8.0 *netlib
liblapacke: 3.8.0 *netlib
libmatio: '1.5'
libnetcdf: 4.6.2
libpcap: '1.8'
libpng: 1.6.35
libprotobuf: '3.8'
librdkafka: 0.11.5
librsvg: 2.44.3
libsecret: '0.18'
libspatialindex: '1.9'
libssh2: '1.8'
libsvm: '3.21'
libtiff: 4.0.9
libunwind: '1.2'
libuuid: 2.32.1
libwebp: 1.0.0
libxml2: '2.9'
lua: '5'
lz4_c: 1.8.3
lzo: '2'
metis: '5.1'
mkl: '2019'
mpfr: '4'
ncurses: '6.1'
netcdf_cxx4: '4.3'
netcdf_fortran: '4.4'
nettle: '3.4'
nlopt: 2.6.*
nspr: '4.20'
nss: '3.39'
ntl: 11.3.2
numpy: '1.14'
occt: '7.3'
openblas: 0.3.6
openjpeg: '2.3'
openssl: 1.1.1a
openturns: 1.13*
pango: '1.40'
pari: '2.11'
perl: '5.26'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
  arpack:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  cairo:
    max_pin: x.x
  curl:
    max_pin: x
  dbus:
    max_pin: x
  expat:
    max_pin: x.x
  ffmpeg:
    max_pin: x.x
  flann:
    max_pin: x.x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  gdal:
    max_pin: x.x
  gdk_pixbuf:
    max_pin: x.x.x
  geotiff:
    max_pin: x.x.x
  glew:
    max_pin: x.x
  glpk:
    max_pin: x.x
  gmp:
    max_pin: x
  graphviz:
    max_pin: x
  harfbuzz:
    max_pin: x
  hdf4:
    max_pin: x.x
  icu:
    max_pin: x
  isl:
    max_pin: x.x
  jasper:
    max_pin: x
  jpeg:
    max_pin: x
  libjpeg_turbo:
    max_pin: x
  json-c:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x.x
  kealib:
    max_pin: x.x
  krb5:
    max_pin: x.x
  libblitz:
    max_pin: x.x
  libcurl:
    max_pin: x
  libdap4:
    max_pin: x.x
  libevent:
    max_pin: x.x.x
  libffi:
    max_pin: x.x
  libgdal:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  libkml:
    max_pin: x.x
  libmatio:
    max_pin: x.x
  libnetcdf:
    max_pin: x.x.x
  libpcap:
    max_pin: x.x
  libpng:
    max_pin: x.x
  libprotobuf:
    max_pin: x.x
  librdkafka:
    max_pin: x.x.x
  librsvg:
    max_pin: x.x
  libspatialindex:
    max_pin: x.x
  libssh2:
    max_pin: x.x
  libsvm:
    max_pin: x.x
  libunwind:
    max_pin: x.x
  libtiff:
    max_pin: x
  libwebp:
    max_pin: x.x
  libxml2:
    max_pin: x.x
  libuuid:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  lzo:
    max_pin: x
  metis:
    max_pin: x.x
  mkl:
    max_pin: x
  mpfr:
    max_pin: x
  ncurses:
    max_pin: x.x
  netcdf-cxx4:
    max_pin: x.x
  netcdf-fortran:
    max_pin: x.x
  nettle:
    max_pin: x.x
  nlopt:
    max_pin: x.x.x
  nss:
    max_pin: x
  nspr:
    max_pin: x
  occt:
    max_pin: x.x
  openblas:
    max_pin: x.x.x
  openturns:
    max_pin: x.x
  openjpeg:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  pango:
    max_pin: x.x
  perl:
    max_pin: x.x.x
  pixman:
    max_pin: x.x
  poppler:
    max_pin: x.x
  proj4:
    max_pin: x.x.x
  qt:
    max_pin: x.x
  readline:
    max_pin: x
  snappy:
    max_pin: x.x.x
  sox:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  sundials:
    max_pin: x.x
  tk:
    max_pin: x.x
  vc:
    max_pin: x
  vlfeat:
    max_pin: x.x.x
  vtk:
    max_pin: x.x.x
  xerces-c:
    max_pin: x.x.x
  xz:
    max_pin: x.x
  zeromq:
    max_pin: x.x
  zlib:
    max_pin: x.x
  zstd:
    max_pin: x.x.x
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  libdeflate:
    max_pin: x.x
pixman: '0.38'
poppler: 0.67.0
proj4: 6.1.0
python: '3.6'
qt: '5.9'
r_base: '3.6'
readline: '8.0'
singular: 4.1.2
snappy: 1.1.7
sox: 14.4.2
sqlite: '3'
sundials: '3.2'
target_goarch: amd64
target_gobin: ${PREFIX}/bin/
target_goexe: ''
target_goos: linux
target_platform: linux-64
tk: '8.6'
vlfeat: 0.9.20
vtk: 8.2.0
x264: 1!152.*
xerces_c: 3.2.2
xz: '5.2'
zeromq: 4.3.1
zip_keys:
- - qt
- - python
zlib: '1.2'
zstd: 1.4.0
